In [1]:
#import statements
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
#create a scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the dimensions of our scalar
scalar.ndim

0

In [6]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
#check the dimensions of our vector
vector.ndim

1

In [10]:
#create a matrix
matrix = tf.constant([[10,10],[2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  3]])>

In [13]:
#check the dimensions of our matrix
matrix.ndim

2

In [20]:
#create another_matrix
another_matrix = tf.constant([[1.,2.],
                              [4.,7.],
                              [9.,6.]],
                             dtype=tf.float16)

In [21]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [4., 7.],
       [9., 6.]], dtype=float16)>

In [22]:
# number of dimentions of another_matix
another_matrix.ndim

2

In [23]:
#Let's create a tensor
tensor = tf.constant([[[1,2,3],[5,6,7]],[[8,9,4]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (Temp/ipykernel_23568/421453776.py, line 2)