In [1]:
#import statements
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
#create a scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the dimensions of our scalar
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
#check the dimensions of our vector
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[10,10],[2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  3]])>

In [7]:
#check the dimensions of our matrix
matrix.ndim

2

In [8]:
#create another_matrix
another_matrix = tf.constant([[1.,2.],
                              [4.,7.],
                              [9.,6.]],
                             dtype=tf.float16)

In [9]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [4., 7.],
       [9., 6.]], dtype=float16)>

In [10]:
# number of dimentions of another_matix
another_matrix.ndim

2

In [21]:
# Let's create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [5, 6, 7]
    ],
    [
        [8, 9, 4],
        [2, 3, 6]
    ]
])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[8, 9, 4],
        [2, 3, 6]]])>

In [15]:
tensor.ndim

3

In [25]:
changable_tensor = tf.Variable([111,23])
unchangable_tensor = tf.constant([111,23])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([111,  23])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([111,  23])>)

In [31]:
#modifying the two tensors
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 23])>

In [33]:
# unchangable_tensor[0].assign(7)
# unchangable_tensor

### Creating Random Tensors

In [132]:
#create random tensors
import time
random_1 = tf.random.Generator.from_seed(int(time.time()))

random_tensor = random_1.normal(shape=(2,3))

random_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.2970339 ,  0.26664338,  0.23242086],
       [-0.63200104, -1.330824  , -0.01727757]], dtype=float32)>

In [160]:
not_shuffled = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
not_shuffled


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [168]:
#shuffing the unshuffled tensor

suffled_tensor = tf.random.shuffle(not_shuffled,seed=int(time.time()))
suffled_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [174]:
tf.ones(shape=(10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

Convert Numpy to tensor

In [186]:
import numpy as np

np_array = np.array([i for i in range(24)])

tensor_array = tf.constant(np_array)

tensor_array

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [192]:
new_tensor = tf.constant(tensor_array,shape=(3,8))

In [202]:
new_tensor.ndim, new_tensor.shape, tf.size(new_tensor).numpy(), new_tensor[0]


AttributeError: 'int' object has no attribute 'numpy'